### ISSUE TITLE
Bridge won't connect to MQTT

### ISSUE THREAD

**Issue by Strider11** [vkorn/hassio-addons#7]
I'll start out by saying I'm a noob and don't really know what I'm doing.
I have Hass.io installed and setup with quite a few things pulling data, but no automations yet.  I have Mosquito MQTT setup along with CloudMQTT and they seem to be talking to each other.  I'm pulling owntracks into Mosquito from CloudMQTT.  So far no matter what combination I've tried, I can't get SmartThingsBridge to talk to either MQTT client.  Below is my current log, options are pointing to Mosquito MQTT using localhost IP (also tried local network IP & duckdns.org address.)  IP, Username & Password match my MQTT broker config in configuration.yaml

starting version 3.2.2
info: Starting SmartThings MQTT Bridge - v1.3.4
info: Loading configuration
info: Loading previous state
info: Perfoming configuration migration
info: Saving current state
info: Connecting to MQTT at mqtt://127.0.0.1:1883
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Invalid password
    at connect (/usr/lib/node_modules/smartthings-mqtt-bridge/node_modules/mqtt-packet/generate.js:147:13)
    at Object.generate (/usr/lib/node_modules/smartthings-mqtt-bridge/node_modules/mqtt-packet/generate.js:11:14)
    at sendPacket (/usr/lib/node_modules/smartthings-mqtt-bridge/node_modules/mqtt/lib/client.js:34:26)
    at MqttClient._setupStream (/usr/lib/node_modules/smartthings-mqtt-bridge/node_modules/mqtt/lib/client.js:263:3)
    at new MqttClient (/usr/lib/node_modules/smartthings-mqtt-bridge/node_modules/mqtt/lib/client.js:209:8)
    at Object.connect (/usr/lib/node_modules/smartthings-mqtt-bridge/node_modules/mqtt/lib/connect/index.js:132:10)
    at connectToMQTT (/usr/lib/node_modules/smartthings-mqtt-bridge/server.js:309:23)
    at /usr/lib/node_modules/smartthings-mqtt-bridge/node_modules/async/lib/async.js:718:13
    at iterate (/usr/lib/node_modules/smartthings-mqtt-bridge/node_modules/async/lib/async.js:262:13)
    at /usr/lib/node_modules/smartthings-mqtt-bridge/node_modules/async/lib/async.js:274:29

**Comment by tboyce021** [comment]
I'm getting the same thing. Anonymous works, but I can't get the passwords working. Did you ever figure this out?

**Comment by tboyce021** [comment]
Actually, my issue was that the password was all numbers and this addon doesn't like that for some reason. I added some letters to the beginning and now it works.

**Comment by Strider11** [comment]
I did.  It has been a while, but I believe the issue for me was port related.

**Comment by marciogranzotto** [comment]
I had the same problem. Created another user on my Mosquitto with a password that contained letters. This is a bug.
